export const escape = s => String(s ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const safe = u => /^(https?:\/\/|mailto:|\/[^/])/.test(u || '') ? escape(u) : '';
const link = (url, title, cls='') => safe(url) ? `<a class="${cls}" href="${safe(url)}">${title}</a>` : '';
const tags = items => `<div class="tags">${items.map(t => `<span>${escape(t)}</span>`).join('')}</div>`;
const list = items => `<ul>${items.map(t => `<li>${escape(t)}</li>`).join('')}</ul>`;
const section = (id, label, title, body) => body ? `<section id="${id}"><div class="section-heading"><p class="eyebrow">${label}</p><h2>${title}</h2></div>${body}</section>` : '';
export function render(data, project) {
  const p = data;
  const nav = [['about','About',p.about.length],['experience','Experience',p.experience.length],['projects','Projects',p.projects.length],['skills','Skills',p.skills.length],['education','Education',p.education.length],['contact','Contact',p.linkedin || p.email || p.github]].filter(x => x[2]);
  const actions = `${link(p.linkedin,'LinkedIn ↗')}${link(p.github,'GitHub ↗')}${link(p.email && `mailto:${p.email}`,'Email ↗')}${p.cv ? `<a class="button" href="${safe(p.cv)}" download>Download CV ↓</a>` : ''}`;
  const projectActions = pr => `${link(pr.github,'GitHub ↗')}${link(pr.demo,'Live demo ↗')}`;
  let body;
  if (project) {
    body = `<div class="project-hero"><a href="/#projects">← All projects</a><p class="eyebrow">Project / ${escape(project.source)}</p><h1>${escape(project.title)}</h1><p class="lead">${escape(project.description)}</p>${tags(project.technologies)}<div class="actions">${projectActions(project)}</div></div>${(project.explanation || []).map((detail,i) => section(`explanation-${i}`, 'Inside the project', escape(detail.title), detail.paragraphs.map(t => `<p class="prose">${escape(t)}</p>`).join(''))).join('')}${section('highlights','Implementation','Technical highlights',project.highlights.length ? list(project.highlights) : '')}${section('screenshots','In detail','Screenshots',project.images.map(im => { const url = /^https?:/.test(im.src) ? im.src : `/assets/${im.src.replace(/^assets\//,'')}`; return `<img class="screenshot" src="${safe(url)}" alt="${escape(im.alt)}" loading="lazy">`; }).join(''))}`;
  } else {
    body = `<section class="hero" id="home"><div><p class="eyebrow">${escape(p.title)}</p><h1>${escape(p.name)}<span class="accent">.</span></h1><p class="lead">${escape(p.summary)}</p>${p.location ? `<p class="location"><span class="dot"></span>${escape(p.location)}</p>` : ''}<div class="actions"><a class="button" href="#projects">Explore my work ↘</a>${p.cv ? `<a href="${safe(p.cv)}" download>Download CV ↓</a>`:''}</div></div>${p.portrait ? `<figure class="portrait-frame"><img class="portrait" src="/${escape(p.portrait)}" alt="Portrait of ${escape(p.name)}" width="480" height="560" fetchpriority="high"><figcaption>${escape(p.title)}</figcaption></figure>` : `<div class="hero-art" aria-hidden="true"><div class="orbit orbit-one"></div><div class="orbit orbit-two"></div><div class="orbit orbit-three"></div><div class="core">AI<span>From models to systems</span></div></div>`}</section>`;
    body += section('about','01 / Profile','Engineering beyond the notebook.', p.about.map(t => `<p class="prose">${escape(t)}</p>${t.endsWith('covers:') ? tags(p.focus) : ''}`).join('') + (!p.about.some(t => t.endsWith('covers:')) && p.focus.length ? tags(p.focus) : ''));
    body += section('experience','02 / Experience','Applied in the real world.', p.experience.map(pr => `<article class="experience"><div><p class="eyebrow">${escape(pr.title)}</p><p>${escape(pr.description)}</p></div><div>${list(pr.highlights)}<a href="/projects/${pr.slug}/">Explore project details ↗</a></div></article>`).join(''));
    if (p.projects.length) body += section('projects','03 / Selected work','Ideas, built into systems.', `<div class="projects">${p.projects.map((pr,i) => `<article class="card"><div class="card-top"><span class="number">${String(i+1).padStart(2,'0')}</span><span class="arrow" aria-hidden="true">↗</span></div><h3><a href="/projects/${pr.slug}/">${escape(pr.title)}</a></h3><p>${escape(pr.description)}</p>${pr.highlights.length ? `<details class="project-preview"><summary>What I built & achieved</summary>${list(pr.highlights)}</details>` : pr.explanation?.length ? `<details class="project-preview"><summary>How it works</summary><p>${escape(pr.explanation[0].paragraphs[0])}</p></details>` : ''}${tags(pr.technologies)}<div class="card-links"><a href="/projects/${pr.slug}/">Explore project details ↗</a>${projectActions(pr)}</div></article>`).join('')}</div>`);
    if (p.skills.length) body += section('skills','04 / Toolkit','Tools behind the work.', `<div class="skills">${p.skills.map(g => `<article><h3>${escape(g.title)}</h3>${tags(g.items)}</article>`).join('')}</div>`);
    body += section('education','05 / Foundations','Education & continuous learning.',p.education.map(e => `<article class="education"><h3>${escape(e.split('\n')[0])}</h3><p>${escape(e.split('\n').slice(1).join(' '))}</p></article>`).join('') + (p.certifications.length ? `<h3 class="subheading">Certifications</h3><div class="certifications">${p.certifications.map(c => `<p>${escape(c)}</p>`).join('')}</div>` : '') + (p.languages.length ? `<h3 class="subheading">Languages</h3>${tags(p.languages)}` : ''));
    if (p.contact || p.linkedin || p.github || p.email || p.cv) body += section('contact','06 / Connect',"Let’s build something useful.",`<p class="lead">${escape(p.contact)}</p><div class="actions">${actions}</div>`);
  }
  return `<!doctype html><html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="description" content="${escape(project?.description || p.summary)}"><meta name="theme-color" content="#0e141b"><title>${escape(project ? `${project.title} | ${p.name}` : `${p.name} | ${p.title}`)}</title><link rel="stylesheet" href="/style.css"></head><body><a class="skip" href="#main">Skip to content</a><header><a class="wordmark" href="/">${escape(p.name)}<span> / Portfolio</span></a><nav aria-label="Main navigation">${nav.map(([id,label]) => `<a href="/#${id}">${label}</a>`).join('')}</nav></header><main id="main">${body}</main><footer><span>${escape(p.name)}</span><a href="/#home">Back to top ↑</a></footer><script src="/motion.js" defer></script></body></html>`;
}
